version: '3'
services:
  app:
    image: lanarich/fast-api-dota2:v2
    container_name: fastapi_app
    ports:
      - "8000:8000" 
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:7
    container_name: redis_app